language: python

cache: pip

python:
- '3.6'
# currently breaking do to pyyaml
#- 'nightly'  # currently 3.7

#matrix:
#  allow_failures:
#  - python: 'nightly'

install:
- make install
- pip freeze

script:
- make lint
- make test
- ./tests/check_tag.py

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
